# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A6rCtLGyOtHbsDbqbmKbSnnRKfOuk8uA
"""

from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import matplotlib
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np

boston = load_boston()
df = pd.DataFrame(boston.data, columns = boston['feature_names'])

df['Price'] = boston.target
new_x = df.drop('Price', axis = 1)
new_y = df['Price']

x_train, x_test, y_train, y_test = train_test_split(new_x, new_y, test_size = 0.3, random_state = 37)
lr = LinearRegression()
rr = Ridge(alpha = 100)
la = Lasso(alpha = 0.000001, max_iter = 10e5)

lr.fit(x_train, y_train)
rr.fit(x_train, y_train)
la.fit(x_train, y_train)

lr_score = lr.score(x_test, y_test)
rr_score = rr.score(x_test, y_test)
la_score = la.score(x_test, y_test)

lr_score1 = lr.score(x_train, y_train)
rr_score1 = rr.score(x_train, y_train)
la_score1 = la.score(x_train, y_train)

coeff_usedrr = np.sum(rr.coef_ != 0)
coeff_usedla = np.sum(la.coef_ != 0)

print('Training score Linear Regression: ',lr_score1)
print('Testing score Linear Regression: ',lr_score)
print('\nTesting score Ridge Regression: ',rr_score)
print('Training score Ridge Regression: ',rr_score1)
print('\nTraining score Lasso Regression: ',la_score1)
print('Testing score Lasso Regression: ',la_score)